name: doantotnghiep
description: "convert book from .pdf, .fb2, .pub. using clean architecture/bloc/firebase. "

publish_to: 'none' # Remove this line if you wish to publish to pub.dev


version: 1.0.0+1

environment:
  sdk: ^3.6.2

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8

  # state management
  flutter_bloc: ^9.1.0
  bloc: ^9.0.0
  equatable: ^2.0.7

  # support localization
  intl: ^0.19.0
  flutter_localization: ^0.3.1

  # storage
  hive_ce: ^2.10.1
  hive_ce_flutter: ^2.2.0
  shared_preferences: ^2.5.2

  # networking
  dio: ^5.8.0+1

  # dependency Injection
  get_it: ^8.0.3

  # navigation
  go_router: ^14.8.1
  google_nav_bar: ^5.0.7

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0


flutter:


  uses-material-design: true
  generate: true
  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/images/
    - assets/logo/
    - assets/images/language/
    - lib/core/localization/l10n/app_en.json
    - lib/core/localization/l10n/app_vi.json
  #   - images/a_dot_ham.jpeg

  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/to/font-from-package
