name: doantotnghiep
description: "convert book from .pdf, .fb2, .pub. using clean architecture/bloc/firebase. "

publish_to: 'none' # Remove this line if you wish to publish to pub.dev


version: 1.0.0+1

environment:
  sdk: ^3.6.2

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  popover: ^0.3.1

  # state management
  flutter_bloc: ^9.1.0
  bloc: ^9.0.0
  equatable: ^2.0.7

  # support localization
  intl: ^0.19.0
  flutter_localization: ^0.3.1

  # storage
  hive_ce: ^2.10.1
  hive_ce_flutter: ^2.2.0
  shared_preferences: ^2.5.2
  uuid: ^4.5.1

  # networking
  dio: ^5.8.0+1
  internet_connection_checker: ^3.0.1
  http: ^1.3.0
  cached_network_image: ^3.3.1
  percent_indicator: ^4.2.4

  # dependency Injection
  get_it: ^8.0.3

  # navigation
  go_router: ^14.8.1
  google_nav_bar: ^5.0.7
  # layoyt
  flutter_screenutil: ^5.9.3
  permission_handler: ^11.4.0
  device_info_plus:

  # File Picker & Reader
  image_picker: ^1.1.2
  file_picker: ^10.0.0
  path_provider: ^2.1.5
  epub_view: ^3.2.0
  epub_decoder: ^0.1.4
  pdf: ^3.8.4
  epubx: ^4.0.0
  syncfusion_flutter_pdfviewer: ^29.1.37

  # firebase
  firebase_auth: ^5.5.1
  firebase_storage: ^12.4.5
  cloud_firestore: ^5.6.5
  firebase_database: ^11.3.5
  firebase_core: ^3.12.1
  firebase_messaging: ^15.2.4
  firebase_app_check:
#  firebase_crashlytics: ^4.3.4
#  firebase_analytics: ^11.4.4
  google_sign_in: ^6.3.0
  sign_in_with_apple: ^6.1.4
  dartz: ^0.10.1
  rxdart: ^0.28.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0

flutter:

  uses-material-design: true
  generate: true
  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/images/
    - assets/logo/
    - assets/images/language/
    - assets/images/empty/
    - assets/images/auth/
    - lib/core/localization/l10n/app_en.json
    - lib/core/localization/l10n/app_vi.json
  #   - images/a_dot_ham.jpeg

  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/to/font-from-package
